services:
  web:
    container_name: web
    restart: unless-stopped
    image: art.azki.com/docker/nginx:alpine
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reports:/mnt/reports:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 1s   
      retries: 3
      start_period: 1s
  generator:
    tty: true
    container_name: report-generator
    restart: no
    hostname: report-generator
    build:
      context: .
      dockerfile: Dockerfile
    command:
        - 'python'
        - 'main.py'
        - '-i'
        - '/mnt/reports/images.txt'
        - '-o'
        - '/mnt/reports/'
        - '-t'
        - '/mnt/reports/html.tmpl'
    volumes:
      - ./reports:/mnt/reports
      - /var/run/docker.sock:/var/run/docker.sock
