apiVersion: batch/v1
kind: CronJob
metadata:
  name: generator-image-sec-scan
  namespace: security
spec:
  schedule: "* * * * *"  # Runs every Sunday  at midnight
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: generator-image-sec-scan
        spec:
          restartPolicy: Never
          containers:
          - name: date-generator
            image: art.azki.com/docker/python:3-alpine
            command: ["python"]
            args: ["/mnt/code/generator.py"]
            volumeMounts:
            - name: image-sec-scan-pvc
              mountPath: /mnt/reports
            - name: images-config
              mountPath: /mnt/images
              readOnly: true
            - name: py-code
              mountPath: /mnt/code
              readOnly: true
          volumes:
          - name: image-sec-scan-pvc
            persistentVolumeClaim:
              claimName: image-sec-scan-pvc
          - name: images-config
            configMap:
              name: images-config
          - name: py-code
            configMap:
              name: py-code
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: images-config
  namespace: security
data:
  list.conf: |
    art.azki.com/docker/alpine:latest
    art.azki.com/docker/nginx:alpine
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: py-code
  namespace: security
data:
  generator.py: |
    import time
    print("Hello from the monthly Python job!")
    time.sleep(30)