apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-sec-scan-pvc
  namespace: security
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-cephfs
